#!/usr/bin/env python3
"""Union限定受入とscheduler衝突訂正を正本化。記録時のnative/ARM再走0。"""
import datetime,json,os,subprocess,sys
from pathlib import Path
sys.setrecursionlimit(max(sys.getrecursionlimit(),1500))
ROOT=Path(__file__).resolve().parents[1];sys.path[:0]=[str(ROOT/'scripts'),str(ROOT)]
import pr16_story_live_probe as t
import pr16_dex_union_failure_actions as isolated_work
import pr16_dex_union_ui as work
import pr16_dex_union_formatter_actions as formatter_work
need,identity,write=work.need,work.identity,work.write
BASE='f0b6d885ddee4a18cd9a599281989009b4d74bfa';RUN=37251844445;JOB=111580919887;ARCHIVE=(11321685327,RUN,203984,'897285fed69d7824fc925125af5799cf04fd270b86b01267018400eb95d4507e')
DIAGNOSTICS=[(11321415212,37251553224,40116,'6900f2467af3a75bb12beeae207aa87719619b10baba2a6f4e9b5bc9c88e610e'),(11321095841,37250937071,40007,'a1d4bd4611aa85cc55f09defe08f867e7d857375c4779be68ba301e454d17c55'),(11319087138,37245820015,618,'71a90e4089c0a77e5ec6e86eefc90b876f168ee418d849f768305d048051d46f'),(11318773032,37246060372,630,'abc7afda92b816220c1d141ede71ab3605be965089f4840385319d586ad4878c'),(11319746971,37247271940,26602,'874c51061d58cdfae5fa1397c0b57b40b28e3403422389a673adadf1dcc4a6fb'),(11319318881,37247754809,877,'2e020bef002b4fd8a9da88bcd2a3c007e37c485e60ef61eb43b879013a94b2cd'),(11319369036,37247902730,7087,'f494d2659f2fcde41612e9bcfb39e11b9a1374b5bf4504a2442fba3e9e3b958a'),(11320295301,37248137574,10332,'256f11806074bb1c501accf89fa2ba6abd177e750538fb455dc72546bfb16848'),(11320140551,37248337419,10436,'f1102aa421404c286c0b0d12d017ee4a7bffb03cd5cc84c7dc24c242d693e866'),(11320757589,37250328812,40240,'3d561f719cdb9712ad0c26974fa505a3db1ad052231aad3c81169bdee537f3cb')]
WF=work.WF;VISUAL='content/modernization/pr16_dex_union_ui_visual_review.json';CODE={WF,VISUAL,'scripts/pr16_dex_union_record.py','.github/workflows/pr16-dex-union-record.yml'}
STATE='content/modernization/pr16_native_supply_resume_20260913.json';DOC='docs/PR16_NATIVE_SUPPLY_RESUME_20260913_JA.md';CP='content/modernization/pr16_dex_union_checkpoint.json';GUIDE=isolated_work.GUIDE;OLDGUIDE='docs/PR16_DEX_MYSTERY_FAILURE_JA.md';EVIDENCE='content/modernization/pr16_dex_union_evidence';LOGS={'design/run_log.md','design/version_log.md'}
OUT=ROOT/'.local/pr16-dex-union-record';PUBLIC=ROOT/'public-dex-union-record'
def git(*args):return subprocess.check_output(['git',*args],cwd=ROOT)
def bindings(paths):return{p:identity((ROOT/p).read_bytes())for p in sorted(paths)}
def current():
 need(os.environ['GITHUB_REPOSITORY']=='dekaazarashi1111-web/pokemon-vega-modern'and os.environ['GITHUB_REF_NAME']=='codex/modernization-followup-20260908'and os.environ['GITHUB_RUN_ATTEMPT']=='1','authorized record');p=t.api('pulls/16');need(p['state']=='open'and p['draft']and not p['merged']and p['head']['sha']==os.environ['GITHUB_SHA'],'sole latest draft HEAD')
def source_guard():
 import pr16_learnset_runtime_record as g
 import pr16_dex_publication as publication
 current();publication.contract(ROOT,'.github/workflows/pr16-dex-union-record.yml',PUBLIC,'pr16-dex-union-record-receipts','scripts/pr16_dex_union_record.py');g.START=BASE;g.CODE=CODE;g.OWNED=set();g.guard()
def archive(spec,kind,ui=False):
 import pr16_dex_publication as publication
 publication.consumer(t.api('actions/artifacts/'+str(spec[0])),'pr16-dex-union-ui-text-only'if ui else'pr16-dex-union-failure-text-only',spec[1])
 z,_=t.archive(spec)
 with z:files={n:z.read(n)for n in z.namelist()}
 folder=OUT/kind;folder.mkdir()
 for n,b in files.items():
  p=Path(n);need(not p.is_absolute()and'..'not in p.parts and len(p.parts)<=3,'bounded archive paths');d=folder/p;d.parent.mkdir(parents=True,exist_ok=True);d.write_bytes(b)
 module=work if ui else isolated_work;old=module.PUBLIC
 try:module.PUBLIC=folder;module.export()
 finally:module.PUBLIC=old
 return files,folder

def record():
 from pr16_learnset_compact_record import publish_resume
 import pr16_resume,pr16_dex_mystery_ui as mg,pr16_dex_start_fault_ui as cold
 current();need(not OUT.exists()and not(ROOT/CP).exists(),'fresh immutable candidate record');OUT.mkdir(parents=True);PUBLIC.mkdir();state=json.loads((ROOT/STATE).read_bytes());protected=dict(state['source_bindings'])
 changed_old='scripts/pr16_dex_mystery_failure.py';old=git('show',isolated_work.BASE+':'+changed_old);needle=b'def apply(before,payload,linked):\n';insert=needle+b' import pr16_dex_subowners as current\n current.require_codec_lease(BASE,len(payload))\n';need(identity(old)==protected[changed_old]and old.count(needle)==1 and(ROOT/changed_old).read_bytes()==old.replace(needle,insert),'historical generator gains only current-subowner collision refusal')
 need(bindings(set(protected)-{changed_old})=={k:v for k,v in protected.items()if k!=changed_old}and state['pending_runs']==[],'all other prior sources and terminal state')
 for run,job,head in[(work.ORIGINAL_RUN,work.ORIGINAL_JOB,work.ORIGINAL_HEAD),(RUN,JOB,BASE)]:
  r=t.api('actions/runs/'+str(run));j=t.api('actions/jobs/'+str(job));need(r['head_sha']==head and r['status']=='completed'and r['conclusion']=='success'and j['run_id']==run and len(j['steps'])==10 and all(s['conclusion']=='success'for s in j['steps']),'both source runs all10 terminal')
 original,of=archive(work.ARCHIVE,'isolated');ui,uf=archive(ARCHIVE,'ui',True);i=json.loads(original['measurement.json']);m=json.loads(ui['measurement.json']);need('failure.json'not in original and'failure.json'not in ui,'successful complete originals')
 need(i['status']=='PASS_ISOLATED_UNION_SAVE_FAILURE_NOTIFICATION'and i['source_head']==work.ORIGINAL_HEAD and i['native_processes']==3 and i['isolated']['cases']==1016,'new Union isolation original')
 need(json.loads(original['isolated-stdout.txt'])==i['isolated']and not original['isolated-stderr.txt'],'whole Union isolation trace')
 for name,cases in [('restored-scheduler',19),('relocated-mystery',816)]:
  rows=[json.loads(x)for x in original[name+'-stdout.txt'].splitlines()];need(rows[-1]==i['regressions'][name]and rows[-1]['cases']==cases and not original[name+'-stderr.txt'],'whole changed-impact regression '+name)
 need(i['candidate']==dict(size=33554432,sha256='1ec42a5031acbb2a3346398edf3a5367372e408c929c28c43307a8fea2ce5e7f')and i['link']['payload']['size']==360,'retained predecessor full isolation receipt')
 build=json.loads(ui['build.json']);need(build==m['formatter_reconstruction']and build['candidate']==m['candidate']==dict(size=33554432,sha256='0180c1804cc368b30bc0ee63ec4f5743d46c707a9f88f45650c47edb375e5315')and build['link']['payload']['size']==408 and build['link']['base']==0x09FFFB28 and build['delta_rollback_exact']and build['ancestor_candidate']==i['candidate'],'complete reconstructed current candidate and old exact inverse')
 fj=t.api('actions/jobs/'+str(work.JOB));fr=t.api('actions/runs/'+str(work.RUN));need(fr['head_sha']==work.BASE and fr['status']=='completed'and fr['conclusion']=='failure'and fj['run_id']==work.RUN and len(fj['steps'])==10 and all(x['conclusion']==('failure'if x['number']==8 else 'success')for x in fj['steps'])and t.api('actions/runs/'+str(work.RUN)+'/artifacts')['artifacts']==[],'formatter168 assertion step succeeded but raw artifact genuinely missing')
 need(build['formatter_assertion_only']==dict(run=work.RUN,job=work.JOB,source=work.BASE,cases=168,measurement_step_success=True,raw_artifact_available=False,upload_path_failure=True,native_reruns=0),'assertion-only evidence never fabricated as raw receipt')
 pl=build['placement'];need(pl['unchanged_owners']==112 and len(pl['owner_byte_audit'])==112 and all(not r['changed']and r['before_sha256']==r['after_sha256']for r in pl['owner_byte_audit'])and pl['allocation']['summaries']['allocation_count']==113 and pl['allocation']['summaries']['overlap_count']==0 and pl['whole_rom_rollback_exact'],'every existing owner byte retained and one new real owner')
 need(pl['tail_reference_audit']['unclassified_candidates']==0 and pl['tail_reference_audit']['literal_candidates']==16 and pl['tail_reference_audit']['thumb_bl_candidates']==1 and len(pl['restored_scheduler_subowners'])==4 and pl['old_mystery_allocation_acceptance_revoked'],'typed placement and collision correction')
 need(m['status']=='PASS_UNION_CHAT_UI_ONLY_FAILURE_SUCCESS_AND_COLD'and m['run_id']==RUN and m['source_head']==BASE and m['native_processes']==12 and m['ram_fixture_bytes_per_ui_process']==21 and m['mystery_fixture_bytes_per_process']==11 and m['register_writes']==0,'six affected UI and six independent cold processes')
 changed_ancestor={'.github/workflows/pr16-dex-union-failure.yml','content/modernization/pr16_dex_union_failure_bindings.json','content/modernization/pr16_dex_union_tail_lease.json',GUIDE,'overlays/dex_owner/dex_union_save_failure.S','scripts/pr16_dex_tail_lease.py','scripts/pr16_dex_union_failure.py','tests/test_pr16_dex_union_failure.py'}
 for report,head,exceptions in[(i,work.ORIGINAL_HEAD,changed_ancestor),(m,BASE,{WF})]:
  for path,b in report['source_bindings'].items():need(identity(git('show',head+':'+path))==b and(path in exceptions or identity((ROOT/path).read_bytes())==b),'whole original source and bounded successor '+path)
 old=git('show',BASE+':'+WF);trigger=('  push:\n    branches: [codex/modernization-followup-20260908]\n    paths: ['+WF+']\n').encode();need(old.count(trigger)==1 and(ROOT/WF).read_bytes()==old.replace(trigger,b'  workflow_dispatch:\n'),'successful UI becomes manual only')
 for group in ('cases','relocated_mystery_cases'):
  for case in m[group]:
   name=case['name'];validator=work.validate_trace if group=='cases'else mg.validate_trace;need(validator(ui[name+'/stdout.txt'],uf/name,m['candidate'],case['mode'])==case['trace'],'all actual UI/renderer/audio events and pixels')
   c=case['cold'];prefix=name+'-cold/cold-'+str(c['counter']);rows=[json.loads(x)for x in ui[prefix+'/stdout.txt'].splitlines()];need([x for x in rows if'observe'in x]==[c['observation']]and[x for x in rows if'mdx'in x]==[c['mdx']]and rows[-1]==c['end']and c['input']==c['output']==case['save'],'independent cold whole trace and FlashRTC');need(cold.screens(rows,uf/prefix)==c['screens'],'all original cold pixels')
 need([(x['name'],x['mode'])for x in m['cases']]==[('main-fault',1),('outer-fault',2),('healthy',0)]and[(x['name'],x['mode'])for x in m['relocated_mystery_cases']]==[('mystery-main-fault',1),('mystery-outer-fault',2),('mystery-healthy',0)],'exact six case names and modes')
 need(sum(len(case['trace']['screens'])+len(case['cold']['screens'])for group in('cases','relocated_mystery_cases')for case in m[group])==30,'exact30 original screens')
 visual=json.loads((ROOT/VISUAL).read_bytes());images={n:identity(b)for n,b in sorted(ui.items())if n.endswith('.ppm')};need(visual['run']==RUN and visual['source_head']==BASE and visual['archive']==list(ARCHIVE)and visual['images']==images and len(images)==visual['screens']==30 and visual['actual_pixels_reviewed']is True,'human visual review bound to exact source run/archive and all30 whole images')
 pixel=visual['union_cold_pixel_comparison'];a=ui[pixel['reference']][15:];b=ui[pixel['compared']][15:];points=[(i//3%240,i//3//240)for i in range(0,len(a),3)if a[i:i+3]!=b[i:i+3]];need(len(points)==pixel['different_pixels']==142 and pixel['bbox_exclusive']==[min(x for x,y in points),min(y for x,y in points),max(x for x,y in points)+1,max(y for x,y in points)+1]==[113,70,128,87]and ui['outer-fault-cold/cold-102/screen-0000.ppm']==ui['healthy-cold/cold-102/screen-0000.ppm']and pixel['other_pixels_identical']and pixel['outer_and_healthy_images_identical']and not pixel['physical_position_shift_observed'],'exact raw PPM pixels: facing-only difference within same player rectangle')
 need(set(i['source_bindings'])==isolated_work.CODE and set(m['source_bindings'])==work.CODE,'complete source-binding key sets')
 for report in(i,m):
  for key in('formal_rom_changed','formal_save_changed','all_nonstart_notifications_accepted'):need(report[key]is False,'unaccepted scope false '+key)
 need(i['all_save_modes_accepted']is False and m['natural_entry_accepted']is False and m['link_transaction_accepted']is False,'no broader mode/transaction acceptance')
 paths=set();evidence=ROOT/EVIDENCE;evidence.mkdir()
 def retain(files,kind):
  for n,b in files.items():
   if Path(n).suffix not in{'.json','.txt'}:continue
   d=evidence/kind/n;d.parent.mkdir(parents=True,exist_ok=True);d.write_bytes(b);paths.add(d.relative_to(ROOT).as_posix())
 retain(original,'isolated');retain(ui,'ui');diagnostics=[]
 for spec in sorted(DIAGNOSTICS,key=lambda x:x[1]):
  files,folder=archive(spec,'diagnostic-'+str(spec[1]),spec[1]>=37247754809);failure=json.loads(files['failure.json']);need(failure['status']=='DIAGNOSTIC_NOT_ACCEPTED','no diagnostic promotion');retain(files,'diagnostic-'+str(spec[1]));diagnostics.append(dict(run=spec[1],artifact=spec[0],failure=failure))
 correction=('旧Mystery候補3bb4c51bは、旧codec余り表示をcurrent sectionと誤認してscheduler clone_complete_generationの先頭128byteを上書きした。以前のisolated/UI成功原本は限定経路の診断として保持するが、配置全体・保存健全性の受入は撤回。健全なouter40a7f38aから再構築し、現在のscheduler3section/codec/112ownerを全byte保持、Mystery/Unionを別のtailownerへ移設した。旧applyはactual subowner重複を拒否する。')
 with(ROOT/OLDGUIDE).open('a')as out:out.write('\n## 後継訂正: scheduler配置衝突\n\n'+correction+'\n\n後継正本は `'+GUIDE+'` と `'+CP+'`。旧1462/1332byteは現在の空き証明ではなく、実空きは2byte gapと28byte suffixだけ。旧候補を正式基準へ採用しない。\n')
 with(ROOT/GUIDE).open('a')as out:out.write('\n## 受入原本とfixture境界\n\n前段隔離run'+str(work.ORIGINAL_RUN)+'はUnion1016＋移設Mystery816＋復元scheduler19の計3process。後続formatter run'+str(work.RUN)+'は変更dispatcher96＋新32byte stack保持72のstep成功だがupload先誤記でraw原本欠落。全候補逆変換で前段1ec42a50と一致させ、未変更1755条件を再走しない。UI run'+str(RUN)+'は両caller各3条件と各cold、計12process/30画像。Unionは失敗時の実printer23byte/保存音0/新A-B待ち/clear1/元cleanup3owner/field帰還、正常は保存音1/元timer。MGは元menu帰還を確認。\n\nUnion入口fixtureはcallback/state13byteに、同一Route506(53,13)を指すdynamicWarp8byteを加えた21byte。Save101の元dynamicWarpは未設定なので、この追加なしに正規通信return環境とはみなせない。各pre/post SHAと全他RAM byte不変を記録し、原本・party・Bag・story flags・位置はhost変更しない。独立cold process自体の追加fixtureは0だが、その入力saveは21byte producer fixture由来であり、fixtureなしの自然cold到達ではない。Union102のcoldはfacingだけ異なり、原本pixel差142は同じplayer領域に限定、背景/位置は一致。自然transitionへの昇格はしない。MGは既存11byte UI入口で、自然通信・受信/削除・旧field window無漏洩を受け入れない。\n\n候補0180c180、tail408byte、残tail832byte。全112既存owner/codecとscheduler3section保持、新113owner/overlap0、16typed apparent literal/typed ThumbBL1、全ROM逆変換を確認。\n')
 cp=dict(schema_version=1,status='PASS_CANDIDATE_UNION_NOTIFICATION_AND_RELOCATED_MYSTERY_UI_ONLY',candidate=m['candidate'],ancestor_isolated=i,current_build=build,ui=m,isolated_run=work.ORIGINAL_RUN,isolated_job=work.ORIGINAL_JOB,isolated_archive=work.ARCHIVE,formatter_assertion_only=build['formatter_assertion_only'],ui_run=RUN,ui_job=JOB,ui_archive=ARCHIVE,diagnostics=diagnostics,correction_ja=correction,old_mystery_candidate_allocation_accepted=False,old_mystery_evidence_preserved=True,scheduler_subowners_restored=True,union_fixture_bytes=21,mystery_fixture_bytes=11,cold_input_fixture_derived=True,visual_review=visual,normal_field_sprite_camera_accepted=False,union102_cold_facing_difference_observed=True,source_bindings=bindings(isolated_work.CODE|formatter_work.CODE|work.CODE|CODE|{OLDGUIDE}),evidence_bindings=bindings(paths),union_failure_notification_accepted=True,mystery_relocated_ui_accepted=True,all_nonstart_notifications_accepted=False,hof_save_failed_repair_accepted=False,all_save_modes_accepted=False,all_consumers_wired=False,early_sector31_fault_accepted=False,sector31_atomicity_accepted=False,natural_entry_accepted=False,link_transaction_accepted=False,formal_rom_changed=False,formal_save_changed=False,record_run=int(os.environ['GITHUB_RUN_ID']),record_source=os.environ['GITHUB_SHA'],record_native_processes=0)
 write(ROOT/CP,cp)
 goal='正式ROM/Save101保持。Unionの誤成功文/SE_SAVEを局所修復し、Mysteryのscheduler衝突を復旧・移設。21byte/11byte UI-onlyと各cold、scheduler19/Union1016/Mystery816を限定受入。次はHOF/共通SaveFailedのtiles16KiB/video/decompression scratch衝突、stat10重複増分とmode4/5 erase再実行、stale selector authority wipeを安全契約へ分離する。早期sector31故障/原子性、全mode、残typed consumerも未完。正式切替・trainer131後半へまだ進まず、最終はシオウPokecenter通常回復/Save/独立coldContinue、雑魚毎Saveなし。'
 runtime=state['story_dex_owner']['runtime_integration'];runtime['mystery_failure'].update(status='RETAINED_DIAGNOSTIC_UI_ONLY_ALLOCATION_REVOKED',allocation_accepted=False,mystery_failure_notification_accepted=False,limited_ui_diagnostic_retained=True,correction_ja=correction,superseded_by=CP);runtime['union_failure']=dict(checkpoint=CP,guide=GUIDE,status=cp['status'],candidate=m['candidate'],isolated_run=work.ORIGINAL_RUN,formatter_assertion_run=work.RUN,formatter_raw_artifact_available=False,ui_run=RUN,record_run=int(os.environ['GITHUB_RUN_ID']),scheduler_subowners_restored=True,union_fixture_bytes=21,mystery_fixture_bytes=11,cold_input_fixture_derived=True,normal_field_sprite_camera_accepted=False,union102_cold_facing_difference_observed=True,formal_rom_changed=False,formal_save_changed=False);runtime['placement']['current_subowner_accounting']=dict(checkpoint=CP,old_suffix_label_is_historical=True,actual_codec_free_subspans=pl['actual_codec_free_subspans'])
 state['bp']['current_stop']='正式ROM/Save101保持。Union失敗文/保存音/入力待ち/帰還を候補限定受入。Mysteryのscheduler重複配置を撤回・復元・別owner移設し影響回帰済み。UI入口はUnion21byte/Mystery11byte fixture。HOF/全mode/残consumer未完。';state['bp']['next_step']=goal;state['next_action'].update(id='CLOSE_HOF_COMMON_FAILURE_AND_REMAINING_SAVE_CONTRACTS',goal_ja=goal,read_paths=[GUIDE,CP,'docs/PR16_DEX_OUTER_QOL_JA.md','docs/PR16_DEX_SAVE_FAILURE_JA.md','docs/PR16_DEX_CONSUMERS_JA.md']);state['observed_head']=os.environ['GITHUB_SHA'];state['observed_head_semantics']='Union限定UI受入とMystery配置撤回/復旧の記録source。正式ROM/Save101不変。'
 state['pending_runs']=[dict(run_id=int(os.environ['GITHUB_RUN_ID']),tested_head=os.environ['GITHUB_SHA'],status='in_progress')];state['source_bindings'].update(bindings(isolated_work.CODE|formatter_work.CODE|work.CODE|CODE|paths|{CP,GUIDE,OLDGUIDE}));state['do_not_repeat'].append('旧Mystery3bb4c51b配置受入はscheduler衝突で撤回。旧余り1462/1332を空き扱いせずcurrent subowner計算を使用。後継0180c180は前段1851条件の原本/未変更1755条件再利用、formatter168条件のstep成功/raw欠落、UI21/11byte由来12process30画面の変更影響のみ受入。formatter168条件はstep成功/raw欠落を区別し重複native再走0。全mode/自然通信へ昇格しない。')
 state['observed_head_checks']=dict(scope_head=BASE,isolated_run=work.ORIGINAL_RUN,formatter_assertion_run=work.RUN,formatter_raw_artifact_available=False,ui_run=RUN,ui_job=JOB,both_all10_steps_success=True,accepted_raw_native_processes=15,diagnostic_native_processes=sum(d['failure']['native_processes']for d in diagnostics),all_attempt_native_processes=16+sum(d['failure']['native_processes']for d in diagnostics),formatter_assertion_native_processes=1,ancestor_raw_cases=1851,reused_unchanged_cases=1755,formatter_asserted_cases=168,union_fixture_bytes=21,mystery_fixture_bytes=11,cold_input_fixture_derived=True,old_mystery_allocation_acceptance_revoked=True,existing_owners_retained=112,new_owner_count=113,all_save_modes_accepted=False,general_ci_known_source_mismatch_not_resolved=True,stage79_cached_not_new_native=True,reason_ja=state['bp']['current_stop']);publish_resume(state);pr16_resume.validate(ROOT)
 stamp=datetime.datetime.now(datetime.timezone.utc).isoformat();entry=f'\n## {stamp}\n- Timestamp: {stamp}\n- Task: USER-20261005-DEX-UNION-FAILURE / Union通知とMystery配置衝突の復旧\n- Version: dex-union-v1\n- Status: DONE（局所候補受入。HOF/全mode/残consumer未完）\n- Summary: {correction}\n- Files changed: Union ASM/generator/typed lease/subowner guard/native/host/workflow、専用CP/evidence、既存Mystery guide訂正、固定MDJSON、両ログ。\n- Verify: ancestor isolated{work.ORIGINAL_RUN}全10step/1016+816+19case/3process、formatter{work.RUN}の168条件step成功/raw artifact欠落（再走0）。UI{RUN}全10step/12process30画像。main故障101/outer末尾故障102/正常102、各cold。候補0180c180/408byte、新113owner/overlap0/112owner全byte/literal16＋DPCM内BL1型分類/全逆変換。記録ARM0/native0。\n- Fixture: Union21=callback-state13+同一field dynamicWarp8、全他RAM byte不変。Mystery11。cold入力はfixture由来で自然通信やfixtureなし到達ではない。正式ROM/Save101不変。\n- Diagnostics: 最初2runは誤suffix仮定でnative0拒否、次isolated1はdisplay fixtureがSB1模様RAMへ重なり保存前停止、UI初回は符号警告でnative0、次はStringCopyのEOS後未使用paddingをコピー済と誤比較してsetup後native1/保存0停止。後継は各文字列EOSまでと元210byte保存領域全体を別々に厳格確認。その後の実UIでFactory32byteの元placeholder破壊を検出しcaller限定stack退避を追加。formatter168条件の測定step成功後にupload先誤記でraw原本を失ったためassertion-onlyへ限定。次の実UIで候補build/全owner保持原本を回収。HelpSystemの元0→1→0とfield再初期化0→0を別検証し、snapshot誤判定を訂正。全失敗は診断原本を保持し受入しない。\n- Next: {goal}\n- Commit: record source={os.environ["GITHUB_SHA"]}; 同branch非force push。\n- Network: 同repoActions/既存入力/固定CFRU WAV witness。公開source/address-size-SHA/text/screensのみ。ROM/rawhex/runtime/入力save/runner/credentials追加公開0。\n'
 for p in LOGS:
  with(ROOT/p).open('a')as out:out.write(entry)
 untouched=set(protected)-{changed_old,OLDGUIDE};need(bindings(untouched)=={k:protected[k]for k in untouched},'every unaffected bound source retained');owned={STATE,DOC,CP,GUIDE,OLDGUIDE,*LOGS}|paths;write(OUT/'owned.json',sorted(owned));write(PUBLIC/'union-record.json',cp);git('add','--',*sorted(owned))
def guard():
 import pr16_resume,pr16_learnset_runtime_record as g
 current();pr16_resume.validate(ROOT);g.START=os.environ['GITHUB_SHA'];g.CODE=set();g.OWNED=set(json.loads((OUT/'owned.json').read_bytes()));g.guard();git('diff','--cached','--check')
def snapshot():
 for p in json.loads((OUT/'owned.json').read_bytes()):need(git('show','HEAD:'+p)==(ROOT/p).read_bytes(),'whole committed record including final newline')
 print('RESULT=DONE TASK=USER-20261005-DEX-UNION-FAILURE VERIFY=PASS COMMIT='+git('rev-parse','HEAD').decode().strip())
def export():
 import pr16_dex_publication as publication
 publication.output(PUBLIC,success='union-record.json',failure=None)
 if not PUBLIC.exists():return
 need(PUBLIC.is_dir()and not PUBLIC.is_symlink(),'dedicated receipt only')
 for p in PUBLIC.iterdir():
  need(p.is_file()and not p.is_symlink()and p.name=='union-record.json','one receipt');b=p.read_bytes();need(0<len(b)<1500000 and b.endswith(b'\n')and b'\0'not in b,'bounded complete JSON');json.loads(b)
if __name__=='__main__':need(len(sys.argv)==2 and sys.argv[1]in('source_guard','record','guard','snapshot','export'),'closed record');globals()[sys.argv[1]]()
