#!/usr/bin/env python3
"""P03 Stage67で接続した全materialized routeを2独立mGBA processで検証する。"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Mapping, NoReturn


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.modernization_p03_stage67 import (  # noqa: E402
    ModernizationP03Stage67Error,
    Stage67Image,
    build_stage67_image,
    fixed_input,
    read_config,
    sha256,
    stable_json,
)


DEFAULT_CONFIG = Path("config/modernization_p03_stage67.json")
TASK = "USER-MODERNIZATION-P03-STAGE67-MGBA-GATE"
FNV_BASIS = 14_695_981_039_346_656_037
FNV_PRIME = 1_099_511_628_211
FNV_MASK = (1 << 64) - 1


class ModernizationP03Stage67MgbaError(RuntimeError):
    """Stage67 mGBA gateのidentity、ABI、実行結果違反。"""


def _fail(message: str) -> NoReturn:
    raise ModernizationP03Stage67MgbaError(message)


def _source_identity(relative: str) -> dict[str, Any]:
    path = ROOT / relative
    if path.is_symlink() or not path.is_file():
        _fail(f"mGBA gate sourceが通常ファイルではありません: {relative}")
    raw = path.read_bytes()
    return {"path": relative, "size": len(raw), "sha256": sha256(raw)}


def _config_relative(config_path: Path) -> str:
    absolute = config_path if config_path.is_absolute() else ROOT / config_path
    try:
        return absolute.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        _fail("mGBA configはworkspace内でなければなりません")


def _parse_symbol(raw: bytes, symbol: str, label: str) -> int:
    try:
        text = raw.decode("ascii")
    except UnicodeDecodeError as error:
        _fail(f"{label}がASCIIではありません: {error}")
    match = re.search(rf"(?m)^{re.escape(symbol)}:\s+([0-9A-Fa-f]{{8}})\s*$", text)
    if match is None:
        _fail(f"{label}に{symbol}がありません")
    return int(match.group(1), 16)


def _header(built: Stage67Image) -> bytes:
    lines = [
        "/* Deterministically generated by run_modernization_p03_stage67_mgba.py. */",
    ]
    for family in ("evolution", "tutor", "egg"):
        lines.append(f"static const struct P03ConsumerCase p03_{family}_cases[] = {{")
        for row in built.runtime_cases[family]:
            if family == "evolution":
                count = len(row["moves"])
            elif family == "tutor":
                count = len(row["set_slots"])
            else:
                count = len(row["moves"])
            if not 0 < count < 256:
                _fail(f"generated {family} countがU8範囲外です")
            lines.append(f"    {{{int(row['species_id'])}U, {count}U}},")
        lines.append("};")
    return ("\n".join(lines) + "\n").encode("ascii")


def _fnv_feed(digest: int, *values: int) -> int:
    for value in values:
        digest ^= value & 0xFF
        digest = digest * FNV_PRIME & FNV_MASK
    return digest


def _fnv_u16(digest: int, value: int) -> int:
    return _fnv_feed(digest, value, value >> 8)


def _expected_digest(built: Stage67Image) -> str:
    digest = FNV_BASIS
    for row in built.runtime_cases["evolution"]:
        species = int(row["species_id"])
        for index, move in enumerate(row["moves"]):
            digest = _fnv_feed(digest, 1)
            digest = _fnv_u16(digest, species)
            digest = _fnv_feed(digest, index)
            digest = _fnv_u16(digest, int(move))
            digest = _fnv_u16(digest, int(move))
    for row in built.runtime_cases["tutor"]:
        species = int(row["species_id"])
        for slot, move in zip(row["set_slots"], row["moves"], strict=True):
            digest = _fnv_feed(digest, 2)
            digest = _fnv_u16(digest, species)
            digest = _fnv_feed(digest, int(slot))
            digest = _fnv_u16(digest, int(move))
            digest = _fnv_feed(digest, 1)
        digest = _fnv_feed(digest, 3)
        digest = _fnv_u16(digest, species)
        digest = _fnv_feed(digest, int(row["negative_slot"]), 0)
    for row in built.runtime_cases["egg"]:
        species = int(row["species_id"])
        moves = row["moves"]
        digest = _fnv_feed(digest, 4)
        digest = _fnv_u16(digest, species)
        digest = _fnv_feed(digest, len(moves))
        for index, move in enumerate(moves):
            digest = _fnv_feed(digest, index)
            digest = _fnv_u16(digest, int(move))
    return f"{digest:016x}"


def _representatives(built: Stage67Image) -> dict[str, list[int]]:
    def ids(family: str) -> list[int]:
        return [int(row["species_id"]) for row in built.runtime_cases[family]]

    evolution = ids("evolution")
    tutor = ids("tutor")
    egg = ids("egg")
    if 534 not in evolution or 24 not in egg or 1048 not in egg:
        _fail("固定representativeがmaterialized casesにありません")
    return {
        "evolution": [evolution[0], evolution[len(evolution) // 2], evolution[-1], 534],
        "tutor": [tutor[0], tutor[len(tutor) // 2], tutor[-1]],
        "egg": [egg[0], egg[len(egg) // 2], egg[-1], 24, 1048],
    }


def _static_inputs(config_path: Path, built: Stage67Image) -> dict[str, Any]:
    config = built.config
    runtime = config["runtime_gate"]
    relative_config = _config_relative(config_path)
    offsets_contract = config["inputs"]["battle_core_offsets"]
    expected_symbols = {
        name: int(address, 16) for name, address in runtime["symbols"].items()
    }
    offsets = []
    for key in ("run_1_path", "run_2_path"):
        contract = {
            "path": offsets_contract[key],
            "size": offsets_contract["size"],
            "sha256": offsets_contract["sha256"],
        }
        raw = fixed_input(ROOT, contract, f"battle-core {key}")
        resolved = {
            name: _parse_symbol(raw, name, f"battle-core {key}")
            for name in expected_symbols
        }
        if resolved != expected_symbols:
            _fail(f"battle-core {key} consumer symbols不一致")
        offsets.append({
            **contract,
            "symbols": {name: f"0x{value:08X}" for name, value in resolved.items()},
        })

    source_paths = [
        relative_config,
        "tools/modernization_p03_stage67.py",
        "tools/modernization_learnsets.py",
        "tools/modernization_identity.py",
        "scripts/run_modernization_p02_acceptance.py",
        runtime["gate_script"],
        runtime["runner_source"],
        *runtime["transitive_sources"],
    ]
    if len(source_paths) != len(set(source_paths)):
        _fail("mGBA gate source一覧が重複しています")
    lib = runtime["libmgba"]
    lib_path = Path(lib["path"])
    if not lib_path.is_file():
        _fail(f"固定libmGBAがありません: {lib_path}")
    lib_raw = lib_path.read_bytes()
    if sha256(lib_raw) != lib["sha256"]:
        _fail("固定libmGBA SHA-256不一致")
    header = _header(built)
    return {
        "config": _source_identity(relative_config),
        "stage66": built.input_audit["stage66_rom"],
        "p02_overlay_parent": built.input_audit["p02_overlay_parent"],
        "stage67": {
            "path": config["outputs"]["rom"],
            "size": len(built.rom),
            "sha256": sha256(built.rom),
        },
        "route_partition": {
            "source_routes": 118528,
            "selected_routes": 118369,
            "non_adopted_move_1063_routes": 159,
            "cumulative_materialized_routes": 51151,
            "selected_routes_deferred": 67218,
        },
        "generated_cases_header": {
            "path": "TEMPORARY/p03_stage67_cases.h",
            "size": len(header),
            "sha256": sha256(header),
        },
        "battle_core_fingerprint": offsets_contract["fingerprint"],
        "offsets": offsets,
        "sources": [_source_identity(path) for path in source_paths],
        "libmgba": {
            "path": lib["path"], "size": len(lib_raw), "sha256": sha256(lib_raw),
        },
    }


def _validate_runner_result(
    result: Mapping[str, Any], expected_sha: str, built: Stage67Image,
) -> None:
    if (
        result.get("schema_version") != 1
        or result.get("status") != "PASS"
        or result.get("classification")
        != "REAL_CONSUMER_DIRECT_CALL_ALL_MATERIALIZED"
        or result.get("rom_sha256") != expected_sha
        or result.get("read_only") is not True
        or result.get("p02_overlay_rows_preserved") != 6
        or result.get("payload_pc_seen") is not True
        or result.get("warnings_errors") != 0
        or result.get("scheduler_e2e") is not False
        or result.get("breeding_e2e") is not False
        or result.get("save_reload_e2e") is not False
        or result.get("full_p03_acceptance") is not False
        or result.get("artifacts_written") != []
    ):
        _fail("mGBA runner top-level contract不一致")
    if result.get("roots") != {
        "level": "0x093A4CAC",
        "tutor": "0x093B1B28",
        "tutor_catalog": "0x0944BC80",
        "egg_primary": "0x09FED0C4",
        "egg_secondary": "0x09FED0C4",
        "egg_scan_limit": 7557,
    }:
        _fail("mGBA runner root readback不一致")
    if result.get("counts") != {
        "evolution_species": 330,
        "evolution_routes": 341,
        "tutor_species": 290,
        "tutor_positive_routes": 740,
        "tutor_negative_calls": 290,
        "egg_species": 450,
        "egg_routes": 2522,
    }:
        _fail("mGBA runner全materialized count不一致")
    instructions = result.get("instructions", {})
    if set(instructions) != {"evolution", "tutor", "egg"} or any(
        isinstance(value, bool) or not isinstance(value, int) or value <= 0
        for value in instructions.values()
    ):
        _fail("mGBA runner instruction count不一致")
    if result.get("semantic_digest_fnv1a64") != _expected_digest(built):
        _fail("mGBA runner semantic digest不一致")
    if result.get("representatives") != _representatives(built):
        _fail("mGBA runner representative集合不一致")
    if result.get("symbols") != {
        "evolution": "0x09114120",
        "tutor": "0x09110228",
        "egg": "0x090EB970",
    }:
        _fail("mGBA runner consumer symbol不一致")


def _run_processes(
    executable: Path, rom_path: Path, rom_sha: str, count: int, timeout: int,
) -> list[dict[str, Any]]:
    processes = [
        subprocess.Popen(
            [str(executable), str(rom_path), rom_sha], cwd=ROOT,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
        for _ in range(count)
    ]
    if len({process.pid for process in processes}) != count:
        for process in processes:
            process.kill()
        _fail("独立mGBA process IDが重複しました")
    results: list[dict[str, Any]] = []
    try:
        for process in processes:
            stdout, stderr = process.communicate(timeout=timeout)
            if process.returncode != 0:
                _fail(f"mGBA runner failed ({process.returncode}): {stderr.strip()}")
            if stderr:
                _fail(f"mGBA runnerがstderrを出力しました: {stderr.strip()}")
            try:
                value = json.loads(stdout)
            except json.JSONDecodeError as error:
                _fail(f"mGBA runner出力がJSONではありません: {error}")
            if not isinstance(value, dict):
                _fail("mGBA runner JSON rootがobjectではありません")
            results.append(value)
    finally:
        for process in processes:
            if process.poll() is None:
                process.kill()
                process.communicate()
    if len(results) != count or any(value != results[0] for value in results[1:]):
        _fail("独立2 mGBA processの結果が一致しません")
    return results


def run_gate(config_path: Path = DEFAULT_CONFIG) -> dict[str, Any]:
    built = build_stage67_image(ROOT, config_path)
    config = built.config
    runtime = config["runtime_gate"]
    process_count = int(runtime["process_runs"])
    if process_count != 2:
        _fail("mGBA gateはexactly 2 independent processes必須です")
    compiler = shutil.which(str(runtime["compiler"]))
    if compiler is None:
        _fail("C compilerがありません")
    version = subprocess.run(
        [compiler, "--version"], cwd=ROOT, capture_output=True, text=True, check=False,
    )
    if version.returncode != 0 or not version.stdout.splitlines():
        _fail("C compiler versionを取得できません")
    header = _header(built)
    local = ROOT / ".local"
    local.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="p03-stage67-mgba-", dir=local) as raw:
        temporary = Path(raw)
        executable = temporary / "p03-stage67-smoke"
        rom_path = temporary / "stage67.gba"
        header_path = temporary / "p03_stage67_cases.h"
        rom_path.write_bytes(built.rom)
        header_path.write_bytes(header)
        command = [
            compiler, *map(str, runtime["compile_flags"]), f"-I{temporary}",
            str(ROOT / runtime["runner_source"]), "-o", str(executable),
            *map(str, runtime["link_flags"]),
        ]
        compiled = subprocess.run(
            command, cwd=ROOT, capture_output=True, text=True,
            timeout=int(runtime["timeout_seconds"]), check=False,
        )
        if compiled.returncode != 0:
            _fail(f"mGBA runner compile failed: {compiled.stdout}{compiled.stderr}")
        if compiled.stdout or compiled.stderr:
            _fail("mGBA runner compileが予期しない出力を生成しました")
        results = _run_processes(
            executable, rom_path, sha256(built.rom), process_count,
            int(runtime["timeout_seconds"]),
        )
    for result in results:
        _validate_runner_result(result, sha256(built.rom), built)
    runner_result = results[0]
    return {
        "schema_version": 1,
        "task": TASK,
        "status": "PASS",
        "classification": "REAL_CONSUMER_DIRECT_CALL_ALL_MATERIALIZED_NOT_E2E",
        "inputs": _static_inputs(config_path, built),
        "execution": {
            "process_runs": 2,
            "independent_processes": True,
            "identical_results": True,
            "compiler": compiler,
            "compiler_version": version.stdout.splitlines()[0],
            "compile_flags": runtime["compile_flags"],
            "link_flags": runtime["link_flags"],
            "runner_result_sha256": sha256(stable_json(runner_result)),
        },
        "runtime_result": runner_result,
        "claims": {
            "exact_generated_stage67_rom": True,
            "p02_overlay_parent_preserved": True,
            "all_materialized_evolution_routes_executed": True,
            "all_materialized_tutor_routes_executed": True,
            "all_materialized_normal_egg_routes_executed": True,
            "egg_primary_secondary_roots_and_limit_executed": True,
            "pichu_volt_tackle_not_coerced_to_normal_egg": True,
            "scheduler_e2e": False,
            "breeding_e2e": False,
            "save_reload_e2e": False,
            "full_p03_acceptance": False,
        },
        "task_completion": "CHECKPOINT_NOT_P03_DONE",
        "artifacts_written": [config["outputs"]["mgba_evidence"]],
    }


def _validate_published(
    evidence: Mapping[str, Any], expected_inputs: Mapping[str, Any],
    expected_sha: str, built: Stage67Image,
) -> None:
    if (
        evidence.get("schema_version") != 1
        or evidence.get("task") != TASK
        or evidence.get("status") != "PASS"
        or evidence.get("classification")
        != "REAL_CONSUMER_DIRECT_CALL_ALL_MATERIALIZED_NOT_E2E"
        or evidence.get("inputs") != expected_inputs
        or evidence.get("task_completion") != "CHECKPOINT_NOT_P03_DONE"
    ):
        _fail("公開済みStage67 mGBA evidence identity不一致")
    result = evidence.get("runtime_result", {})
    _validate_runner_result(result, expected_sha, built)
    execution = evidence.get("execution", {})
    if (
        execution.get("process_runs") != 2
        or execution.get("independent_processes") is not True
        or execution.get("identical_results") is not True
        or execution.get("runner_result_sha256") != sha256(stable_json(result))
    ):
        _fail("公開済みStage67 mGBA 2-process binding不一致")
    claims = evidence.get("claims", {})
    required_true = (
        "exact_generated_stage67_rom", "p02_overlay_parent_preserved",
        "all_materialized_evolution_routes_executed",
        "all_materialized_tutor_routes_executed",
        "all_materialized_normal_egg_routes_executed",
        "egg_primary_secondary_roots_and_limit_executed",
        "pichu_volt_tackle_not_coerced_to_normal_egg",
    )
    required_false = (
        "scheduler_e2e", "breeding_e2e", "save_reload_e2e", "full_p03_acceptance",
    )
    if any(claims.get(key) is not True for key in required_true) or any(
        claims.get(key) is not False for key in required_false
    ):
        _fail("公開済みStage67 mGBA claim境界不一致")


def validate_published_gate(
    config_path: Path = DEFAULT_CONFIG,
    *, stage67_bytes: bytes | None = None, built: Stage67Image | None = None,
) -> dict[str, Any]:
    resolved = built if built is not None else build_stage67_image(ROOT, config_path)
    if stage67_bytes is not None and stage67_bytes != resolved.rom:
        _fail("supplied Stage67 bytesがgenerator結果と一致しません")
    expected_inputs = _static_inputs(config_path, resolved)
    path = ROOT / resolved.config["outputs"]["mgba_evidence"]
    if path.is_symlink() or not path.is_file():
        _fail(f"公開済みStage67 mGBA evidenceがありません: {path}")
    raw = path.read_bytes()
    try:
        evidence = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        _fail(f"公開済みStage67 mGBA evidenceがJSONではありません: {error}")
    if not isinstance(evidence, dict) or raw != stable_json(evidence):
        _fail("公開済みStage67 mGBA evidenceが決定的JSONではありません")
    _validate_published(evidence, expected_inputs, sha256(resolved.rom), resolved)
    return evidence


def _write(path: Path, raw: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        dir=path.parent, prefix=f".{path.name}.", delete=False,
    ) as stream:
        stream.write(raw)
        temporary = Path(stream.name)
    os.replace(temporary, path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("run", "check"))
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args(argv)
    try:
        if args.mode == "run":
            result = run_gate(args.config)
            config = read_config(ROOT, args.config)
            _write(ROOT / config["outputs"]["mgba_evidence"], stable_json(result))
        else:
            result = validate_published_gate(args.config)
    except (
        OSError, KeyError, TypeError, ValueError, subprocess.SubprocessError,
        ModernizationP03Stage67Error, ModernizationP03Stage67MgbaError,
    ) as error:
        print(f"MODERNIZATION_P03_STAGE67_MGBA_{args.mode.upper()}=FAIL", file=sys.stderr)
        print(str(error), file=sys.stderr)
        return 1
    counts = result["runtime_result"]["counts"]
    print(
        f"MODERNIZATION_P03_STAGE67_MGBA_{args.mode.upper()}=PASS "
        f"rom={result['runtime_result']['rom_sha256']} processes=2 "
        f"routes={counts['evolution_routes'] + counts['tutor_positive_routes'] + counts['egg_routes']} "
        "consumers=3 completion=CHECKPOINT_NOT_P03_DONE"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
