"""Bind old runtime evidence to an archived Git blob, never to a newer runner.

Only the reviewed CPU-pipeline successor is allowed. Both source identities are
checked, so neither a changed archive nor an unrelated current edit is hidden.
No runtime result or ROM is generated by this module.
"""
from pathlib import Path
import hashlib

COMMIT = '137c6945c6bf5c633944ddd5287dffca9c5692c0'
SOURCE = 'tools/mgba_battle_core_smoke.c'
ARCHIVE = f'content/modernization/p08_historical_sources/{COMMIT}/{SOURCE}'
HISTORICAL = (94532, '6a4c72232388e4fdf5f4c48a0f5f825193b6977ad8a117d70477b7d595982e23')
CURRENT = (94688, 'ed9875695ca60c61960685ac2f8e810a183c8eedd703e56545d67bde3df5cf24')
GIT_BLOB = '4ebb223fd120395131ec7ddfcbbaee4721c72a66'
BINDINGS = frozenset(('P02_STAGE64_MGBA', 'P02_ACTUAL_CONSUMER_ACCEPTANCE', 'P03_STAGE67_MGBA'))


def _read(root: Path, relative: str) -> bytes:
    path = root / relative
    if path.is_symlink() or not path.is_file():
        raise ValueError(f'historical source is not a regular file: {relative}')
    parent = path.parent
    while parent != root:
        if parent.is_symlink():
            raise ValueError(f'historical source has a symlink parent: {relative}')
        parent = parent.parent
    return path.read_bytes()


def _verify(raw: bytes, expected: tuple[int, str], label: str) -> None:
    if (len(raw), hashlib.sha256(raw).hexdigest()) != expected:
        raise ValueError(f'historical source identity drift: {label}')


def resolve(root: Path, row: dict, tracked: set[str], binding: str):
    """Return the exact archived bytes only for this explicitly adopted lineage."""
    if row.get('path') != SOURCE or binding not in BINDINGS:
        return None
    if (row.get('size'), row.get('sha256')) != HISTORICAL:
        raise ValueError('unapproved historical source declaration')
    if SOURCE not in tracked or ARCHIVE not in tracked:
        raise ValueError('both historical and current sources must be tracked')
    root = root.resolve()
    current = _read(root, SOURCE)
    archived = _read(root, ARCHIVE)
    _verify(current, CURRENT, SOURCE)
    _verify(archived, HISTORICAL, ARCHIVE)
    if hashlib.sha1(f'blob {len(archived)}\0'.encode() + archived).hexdigest() != GIT_BLOB:
        raise ValueError('historical Git blob mismatch')
    return archived, {
        'mode': 'EXACT_HISTORICAL_GIT_BLOB_WITH_PINNED_CURRENT_SUCCESSOR',
        'commit': COMMIT, 'git_blob': GIT_BLOB, 'archive_path': ARCHIVE,
        'current_source': {'path': SOURCE, 'size': CURRENT[0], 'sha256': CURRENT[1]},
        'historical_result_relabelled_as_current': False,
    }
