#ifndef MODERNIZATION_FLOETTE_GIFT_H
#define MODERNIZATION_FLOETTE_GIFT_H

#include <stdint.h>

#define MODERNIZATION_FLOETTE_GIFT_ABI_VERSION 0xA169u
#define MODERNIZATION_FLOETTE_GIFT_SPECIES 1029u
#define MODERNIZATION_FLOETTE_GIFT_BASE_SPECIES 959u
#define MODERNIZATION_FLOETTE_GIFT_NATIONAL_DEX 670u
#define MODERNIZATION_FLOETTE_GIFT_LEVEL 50u
#define MODERNIZATION_FLOETTE_GIFT_CLAIM_FLAG 0x14CDu
#define MODERNIZATION_FLOETTE_GIFT_KEY_STONE_ITEM 580u
#define MODERNIZATION_FLOETTE_GIFT_COLLECTION_BIT 850u

typedef enum ModernizationFloetteGiftResult {
    FLOETTE_GIFT_RESULT_SUCCESS = 0,
    FLOETTE_GIFT_RESULT_ALREADY_CLAIMED = 1,
    FLOETTE_GIFT_RESULT_LOCKED = 3,
    FLOETTE_GIFT_RESULT_NO_CAPACITY = 4,
    FLOETTE_GIFT_RESULT_PERSIST_FAILED = 5,
    FLOETTE_GIFT_RESULT_BUSY = 6,
    FLOETTE_GIFT_RESULT_ENGINE_REJECTED = 7,
    FLOETTE_GIFT_RESULT_ROLLBACK_FAILED = 8
} ModernizationFloetteGiftResult;

uint16_t FloetteGift_Probe(void);
uint16_t FloetteGift_Claim(void);
uint16_t FloetteGift_IsFormObtained(void);
uint16_t FloetteGift_IsNationalDexSeen(void);
uint16_t FloetteGift_IsNationalDexCaught(void);

#endif /* MODERNIZATION_FLOETTE_GIFT_H */
